apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wcc-emp-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      # git repository to get the variables from
      repoURL: https://github.com/mperendija/gitops-testing.git
      # branch used to get the variables from
      revision: values-testing
      files:
      # path to the directory that includes directories to read as variables
      - path: tenants/**/config-tenant.json
  template:
    metadata:
      # basename is the name of the directory not the full path
      name: '{{alias}}'
    spec:
      project: tenants
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        # source repo, in this example both repositories are the same
        repoURL: https://github.com/mperendija/gitops-testing.git
        targetRevision: values-testing
        # path to read manifests from, here it's the full path not only the name of the directory
        path: tenant-template
        # plugin:
        #   name: kustomize-build-with-helm
        helm:
          valueFiles:
            - "values.yaml"
            - "../tenants/{{alias}}/values-over.yaml"
      destination:
        server: https://kubernetes.default.svc
        # different namespaces named after the directories names to be used as destinations
        namespace: '{{alias}}'