apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wcc-emp-project-applicationset-{{ .Values.alias }}
  namespace: argocd
spec:
  generators:
    - git:
        # git repository to get the variables from
        repoURL: https://github.com/mperendija/gitops-testing.git
        # branch used to get the variables from
        revision: tenant-projects-test
        files:
          # path to the directory that includes directories to read as variables
          - path: tenants/{{ .Values.alias }}/**/config-project.json
  template:
    metadata:
      # basename is the name of the directory not the full path
      name: 'project-{{projectId}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        # source repo, in this example both repositories are the same
        repoURL: https://github.com/mperendija/gitops-testing.git
        targetRevision: tenant-projects-test
        # path to read manifests from, here it's the full path not only the name of the directory
        path: 'project-template/{{type}}'
        # plugin:
        #   name: kustomize-build-with-helm
        helm:
          valueFiles:
            - "values.yaml"
            - "../../tenants/{{alias}}/project-{{projectId}}/values-over.yaml"
      destination:
        server: https://kubernetes.default.svc
        # different namespaces named after the directories names to be used as destinations
        namespace: '{{alias}}'