apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: testchart
  releaseName: testchart
  repo: https://github.com/mperendija/gitops-testing/tenant-helm
resources:
  - ../../tenant-helm

namespace: zr

configMapGenerator:
  - name: helmconfmap
    behavior: merge
    literals:
      - newprop=new
