apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: testchart
  version: 0.1.0
resources:
  - ../../tenant-helm

namespace: zr

configMapGenerator:
  - name: helmconfmap
    behavior: merge
    literals:
      - newprop=new
