apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../tenant-manifest

namespace: nbg

configMapGenerator:
  - name: test-configmap
    behavior: merge
    literals:
      - database=nbg
      - newenv=works
