apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../tenant-helm

namespace: zr

configMapGenerator:
  - name: helmconfmap
    behavior: merge
    literals:
      - newprop=new
